package com.pingcap.tispark.tpcc

import org.apache.spark.sql.types._

object TPCCSchema {
  val warehouse: StructType = new StructType()
    .add("w_id", IntegerType, nullable = true)
    .add("w_name", StringType, nullable = true)
    .add("w_street_1", StringType, nullable = true)
    .add("w_street_2", StringType, nullable = true)
    .add("w_city", StringType, nullable = true)
    .add("w_state", StringType, nullable = true)
    .add("w_zip", StringType, nullable = true)
    .add("w_tax", FloatType, nullable = true)
    .add("w_ytd", FloatType, nullable = true)

  val district: StructType = new StructType()
    .add("d_id", IntegerType, nullable = false)
    .add("d_w_id", IntegerType, nullable = false)
    .add("d_name", StringType, nullable = true)
    .add("d_street_1", StringType, nullable = true)
    .add("d_street_2", StringType, nullable = true)
    .add("d_city", StringType, nullable = true)
    .add("d_state", StringType, nullable = true)
    .add("d_zip", StringType, nullable = true)
    .add("d_tax", FloatType, nullable = true)
    .add("d_ytd", FloatType, nullable = true)
    .add("d_next_o_id", IntegerType, nullable = true)

  val item: StructType = new StructType()
    .add("i_id", IntegerType, nullable = false)
    .add("i_im_id", IntegerType, nullable = false)
    .add("i_name", StringType, nullable = true)
    .add("i_price", FloatType, nullable = true)
    .add("i_data", StringType, nullable = true)

  val customer: StructType = new StructType()
    .add("c_id", IntegerType, nullable = false)
    .add("c_d_id", IntegerType, nullable = false)
    .add("c_w_id", IntegerType, nullable = false)
    .add("c_first", StringType, nullable = true)
    .add("c_middle", StringType, nullable = true)
    .add("c_last", StringType, nullable = true)
    .add("c_street_1", StringType, nullable = true)
    .add("c_street_2", StringType, nullable = true)
    .add("c_city", StringType, nullable = true)
    .add("c_state", StringType, nullable = true)
    .add("c_zip", StringType, nullable = true)
    .add("c_phone", StringType, nullable = true)
    .add("c_since", TimestampType, nullable = true)
    .add("c_credit", StringType, nullable = true)
    .add("c_credit_lim", FloatType, nullable = true)
    .add("c_discount", FloatType, nullable = true)
    .add("c_balance", FloatType, nullable = true)
    .add("c_ytd_payment", IntegerType, nullable = true)
    .add("c_payment_cnt", IntegerType, nullable = true)
    .add("c_delivery_cnt", IntegerType, nullable = true)
    .add("c_data", StringType, nullable = true)

  val history: StructType = new StructType()
    .add("H_C_ID", IntegerType, nullable = true)
    .add("H_C_D_ID", IntegerType, nullable = true)
    .add("H_C_W_ID", IntegerType, nullable = true)
    .add("H_D_ID", IntegerType, nullable = true)
    .add("H_W_ID", IntegerType, nullable = false)
    .add("H_DATE", TimestampType, nullable = false)
    .add("H_AMOUNT", FloatType, nullable = true)
    .add("H_DATA", StringType, nullable = true)

  val stock: StructType = new StructType()
    .add("s_i_id", IntegerType, nullable = false)
    .add("s_w_id", IntegerType, nullable = false)
    .add("s_quantity", IntegerType, nullable = false)
    .add("s_dist_01", StringType, nullable = true)
    .add("s_dist_02", StringType, nullable = true)
    .add("s_dist_03", StringType, nullable = true)
    .add("s_dist_04", StringType, nullable = true)
    .add("s_dist_05", StringType, nullable = true)
    .add("s_dist_06", StringType, nullable = true)
    .add("s_dist_07", StringType, nullable = true)
    .add("s_dist_08", StringType, nullable = true)
    .add("s_dist_09", StringType, nullable = true)
    .add("s_dist_10", StringType, nullable = true)
    .add("s_ytd", IntegerType, nullable = true)
    .add("s_order_cnt", IntegerType, nullable = true)
    .add("s_remote_cnt", IntegerType, nullable = true)
    .add("s_data", StringType, nullable = true)

  val orders: StructType = new StructType()
    .add("o_w_id", IntegerType, nullable = true)
    .add("o_d_id", IntegerType, nullable = true)
    .add("o_id", IntegerType, nullable = true)
    .add("o_c_id", IntegerType, nullable = true)
    .add("o_carrier_id", IntegerType, nullable = true)
    .add("o_ol_cnt", IntegerType, nullable = true)
    .add("o_all_local", IntegerType, nullable = true)
    .add("o_entry_d", TimestampType, nullable = true)

  val new_orders: StructType = new StructType()
    .add("no_o_id", IntegerType, nullable = false)
    .add("no_d_id", IntegerType, nullable = false)
    .add("no_d_id", IntegerType, nullable = false)

  val order_line: StructType = new StructType()
    .add("OL_O_ID", IntegerType, nullable = false)
    .add("OL_D_ID", IntegerType, nullable = false)
    .add("OL_W_ID", IntegerType, nullable = false)
    .add("OL_NUMBER", IntegerType, nullable = false)
    .add("OL_I_ID", IntegerType, nullable = false)
    .add("OL_SUPPLY_W_ID", IntegerType, nullable = false)
    .add("OL_DELIVERY_D", TimestampType, nullable = false)
    .add("OL_QUANTITY", IntegerType, nullable = false)
    .add("OL_AMOUNT", FloatType, nullable = false)
    .add("OL_DIST_INFO", StringType, nullable = false)
}
